DotNET_Projects/BulkyBook/BulkyBookWeb/Models/Category.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace BulkyBookWeb.Models
{
    public class Category
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        [DisplayName("Display order")]
        [Range(1,100,ErrorMessage ="Display order must be between 1 and 100 only!!.")]
        public int DisplayOrder { get; set; }
        public DateTime CreatedDateTime { get; set; } = DateTime.Now; 

    }
}

DotNET_Projects/BulkyBook/BulkyBookWeb/Models/ErrorViewModel.cs
namespace BulkyBookWeb.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DotNET_Projects/BulkyBook/BulkyBookWeb/Models/Usersdata.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Data;

namespace BulkyBookWeb.Models
{
    public class Usersdata
    {
        [Key]
        public int Id { get; set; }
        [Required]
        public string FirstName { get; set; }
        public string LastName { get; set; }

        [DisplayName("Age")]
        public int Age { get; set; }
        public string Gender { get; set; }
        public string Profession { get; set; }
        public DateTime Dateofcreation { get; set; } = DateTime.Now;
       
    }
}

DotNET_Projects/BulkyBook/BulkyBookWeb/Controllers/CategoryController.cs
using BulkyBookWeb.Data;
using BulkyBookWeb.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;



namespace BulkyBookWeb.Controllers;

public class CategoryController : Controller
{
    private readonly ApplicationDbContext _db;
    public CategoryController(ApplicationDbContext db)
    {
        _db = db;
    }
    public IActionResult Index()
    {
        IEnumerable<Category> objCategoryList = _db.Categories;
        return View(objCategoryList);
    }

    //GET
    public IActionResult Create()
    {
        return View();
    }

    //Post
    [HttpPost] //want to add post
    [ValidateAntiForgeryToken] // for validation
    public IActionResult Create(Category Obj)
    {
        if(Obj.Name == Obj.DisplayOrder.ToString())
        {
            ModelState.AddModelError("name", "The Displayorder cannot exactly match the name");
        }
        if (ModelState.IsValid)
        {
            _db.Categories.Add(Obj); //add changes or data
            _db.SaveChanges(); // save data
            TempData["success"] = "Category created successfully.";
            return RedirectToAction("Index");
        }
        return View(Obj);
        
    }
    //GET
    public IActionResult Edit(int? id)
    {
        if(id == null || id == 0)
        {
            return NotFound();
        }
        var categoryFromDb = _db.Categories.Find(id);
        //different types
        //var categoryFromDbFirst = _db.Categories.FirstOrDefault(u => u.Id == id); 
        //var categoryFromDbSingle = _db.Categories.SingleOrDefault(u => u.Id == id);

        if(categoryFromDb == null)
        {
            return NotFound();
        }
        return View(categoryFromDb);
    }

    //Post
    [HttpPost] //want to add post
    [ValidateAntiForgeryToken] // for validation
    public IActionResult Edit(Category Obj)
    {
        if (Obj.Name == Obj.DisplayOrder.ToString())
        {
            ModelState.AddModelError("name", "The Displayorder cannot exactly match the name");
        }
        if (ModelState.IsValid)
        {
            _db.Categories.Update(Obj); //add changes or data
            _db.SaveChanges(); // save data
            TempData["success"] = "Category updated successfully.";
            return RedirectToAction("Index");
        }
        return View(Obj);

    }

    //GET
    public IActionResult Delete(int? id)
    {
        if (id == null || id == 0)
        {
            return NotFound();
        }
        var categoryFromDb = _db.Categories.Find(id);
        //different types
        //var categoryFromDbFirst = _db.Categories.FirstOrDefault(u => u.Id == id); 
        //var categoryFromDbSingle = _db.Categories.SingleOrDefault(u => u.Id == id);

        if (categoryFromDb == null)
        {
            return NotFound();
        }
        return View(categoryFromDb);
    }

    //Post
    [HttpPost,ActionName("Delete")      ] 
    [ValidateAntiForgeryToken] 
    public IActionResult DeletePOST(int? id)
    {
        var obj = _db.Categories.Find(id);
        if(obj == null)
        {
            return NotFound();
        }
        
            _db.Categories.Remove(obj); //add changes or data
            _db.SaveChanges(); // save data
            TempData["success"] = "Category deleted successfully.";
        return RedirectToAction("Index");
        
       

    }
}

DotNET_Projects/BulkyBook/BulkyBookWeb/Controllers/HomeController.cs
using BulkyBookWeb.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BulkyBookWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DotNET_Projects/BulkyBook/BulkyBookWeb/Controllers/UsersdataController.cs
using BulkyBookWeb.Data;
using BulkyBookWeb.Models;
using Microsoft.AspNetCore.Mvc;

namespace BulkyBookWeb.Controllers
{ 
    public class UsersdataController : Controller
    {
        private readonly ApplicationDbContext _db;
        public UsersdataController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Usersdata> objUsersList = _db.UsersData;
            return View(objUsersList);
        }
        //get
        public IActionResult Create()
        {
            return View();
        }

        //post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(Usersdata objuser)
        {
            if (objuser.FirstName == objuser.LastName)
            {
                ModelState.AddModelError("firstname", "The lastName cannot exactly match the FirstName.");
            }
            if (ModelState.IsValid)
            {
                _db.UsersData.Add(objuser);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(objuser);
        }
            
        public IActionResult Edit(int? id)
        {
            if(id == null || id == 0)
            {
                return NotFound();
            }
            var userFromDb = _db.UsersData.Find(id);
            if(userFromDb == null)
            {
                return NotFound();
            }

            return View(userFromDb);
        }
        //post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(Usersdata objuser)
        {
            if (objuser.FirstName == objuser.LastName)
            {
                ModelState.AddModelError("firstname", "The lastName cannot exactly match the FirstName.");
            }
            if (ModelState.IsValid)
            {
                _db.UsersData.Update(objuser);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(objuser);
        }

        public IActionResult Delete(int? id)
        {
            if(id == null || id == 0)
            {
                return NotFound();
            }
            var delId = _db.UsersData.Find(id);
            if(delId == null)
            {
                return NotFound();
            }
            return View(delId);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj = _db.UsersData.Find(id);
            if(obj == null)
            {
                return NotFound();
            }
            _db.UsersData.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

       


    }

}

DotNET_Projects/BulkyBook/BulkyBookWeb/Views/CategoriesTemporary/Create.cshtml
@model BulkyBookWeb.Models.Category

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Category</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DisplayOrder" class="control-label"></label>
                <input asp-for="DisplayOrder" class="form-control" />
                <span asp-validation-for="DisplayOrder" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedDateTime" class="control-label"></label>
                <input asp-for="CreatedDateTime" class="form-control" />
                <span asp-validation-for="CreatedDateTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

DotNET_Projects/BulkyBook/BulkyBookWeb/Views/CategoriesTemporary/Delete.cshtml
@model BulkyBookWeb.Models.Category

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Category</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DisplayOrder)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DisplayOrder)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDateTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDateTime)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DotNET_Projects/BulkyBook/BulkyBookWeb/Views/CategoriesTemporary/Details.cshtml
@model BulkyBookWeb.Models.Category

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Category</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DisplayOrder)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DisplayOrder)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDateTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDateTime)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

DotNET_Projects/BulkyBook/BulkyBookWeb/Views/CategoriesTemporary/Edit.cshtml
@model BulkyBookWeb.Models.Category

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Category</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DisplayOrder" class="control-label"></label>
                <input asp-for="DisplayOrder" class="form-control" />
                <span asp-validation-for="DisplayOrder" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedDateTime" class="control-label"></label>
                <input asp-for="CreatedDateTime" class="form-control" />
                <span asp-validation-for="CreatedDateTime" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

DotNET_Projects/BulkyBook/BulkyBookWeb/Views/CategoriesTemporary/Index.cshtml
@model IEnumerable<BulkyBookWeb.Models.Category>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DisplayOrder)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedDateTime)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DisplayOrder)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedDateTime)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

DotNET_Projects/BulkyBook/BulkyBookWeb/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome to Asp.Netcore Mvc</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

DotNET_Projects/BulkyBook/BulkyBookWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BulkyBookWeb</title>
    <link rel="stylesheet" href="~/css/bootsThems.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BulkyBookWeb.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
</head>
<body>
    <header>
       
        
        
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Navbar</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Usersdata" asp-action="Index">Users Data</a>
                        </li>
                       

                        @*<li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="#">Action</a>
                                <a class="dropdown-item" href="#">Another action</a>
                                <a class="dropdown-item" href="#">Something else here</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Separated link</a>
                            </div>
                        </li>*@
                    </ul>
                    <form class="d-flex">
                        <input class="form-control me-sm-2" type="search" placeholder="Search">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </div>
            </div>
        </nav>



        



       
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notifications" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - BulkyBookWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

DotNET_Projects/BulkyBook/BulkyBookWeb/Views/Shared/_Notifications.cshtml
@if(TempData["success"] != null){
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}
@if(TempData["error"]!=null){
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}

DotNET_Projects/BulkyBook/BulkyBookWeb/Views/Usersdata/Create.cshtml
@model Usersdata

<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Create UserData</h2>
            <hr />
        </div>
       @* <div asp-validation-summary="All"></div>*@
        <div class="mb-2">
            <label asp-for="FirstName"></label>
            <input asp-for="FirstName" class="form-control" />
            <span asp-validation-for="FirstName" class="text-danger"></span>
        </div>
        <div class="mb-2">
            <label asp-for="LastName"></label>
            <input asp-for="LastName"  class="form-control"/>
            <span asp-validation-for="LastName" class="text-danger"></span>
        </div>
        <div class="mb-2">
            <label asp-for="Age"></label>
            <input asp-for="Age"  class="form-control"/>
            <span asp-validation-for="Age" class="text-danger"></span>
        </div>
        <div class="mb-2">
            <label asp-for="Gender"></label>
            <input asp-for="Gender" class="form-control" />
            <span asp-validation-for="Gender" class="text-danger"></span>
        </div>
        <div class="mb-2">
            <label asp-for="Profession"></label>
            <input asp-for="Profession" class="form-control" />
            <span asp-validation-for="Profession" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
        <a asp-asp-controller="Userdata" asp-action="Index" class="btn btn-secondary" style="width:150px">Back to List</a>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial.cshtml" />
    }
}

DotNET_Projects/BulkyBook/BulkyBookWeb/Views/Usersdata/Delete.cshtml
@model Usersdata

<form method="post" asp-action="Delete">
    <input asp-for="Id" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Delete UserData</h2>
            <hr />
        </div>
       @* <div asp-validation-summary="All"></div>*@
        <div class="mb-2">
            <label asp-for="FirstName"></label>
            <input asp-for="FirstName" class="form-control" disabled/>
          
        </div>
        <div class="mb-2">
            <label asp-for="LastName"></label>
            <input asp-for="LastName"  class="form-control" disabled/>
            
        </div>
        <div class="mb-2">
            <label asp-for="Age"></label>
            <input asp-for="Age"  class="form-control" disabled/>
           
        </div>
        <div class="mb-2">
            <label asp-for="Gender"></label>
            <input asp-for="Gender" class="form-control" disabled/>
            
        </div>
        <div class="mb-2">
            <label asp-for="Profession"></label>
            <input asp-for="Profession" class="form-control" disabled/>
            
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Delete</button>
        <a asp-asp-controller="Userdata" asp-action="Index" class="btn btn-secondary" style="width:150px">Back to List</a>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial.cshtml" />
    }
}

DotNET_Projects/BulkyBook/BulkyBookWeb/Views/Usersdata/Edit.cshtml
@model Usersdata

<form method="post" asp-action="Edit">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Edit UserData</h2>
            <hr />
        </div>
       @* <div asp-validation-summary="All"></div>*@
        <div class="mb-2">
            <label asp-for="FirstName"></label>
            <input asp-for="FirstName" class="form-control" />
            <span asp-validation-for="FirstName" class="text-danger"></span>
        </div>
        <div class="mb-2">
            <label asp-for="LastName"></label>
            <input asp-for="LastName"  class="form-control"/>
            <span asp-validation-for="LastName" class="text-danger"></span>
        </div>
        <div class="mb-2">
            <label asp-for="Age"></label>
            <input asp-for="Age"  class="form-control"/>
            <span asp-validation-for="Age" class="text-danger"></span>
        </div>
        <div class="mb-2">
            <label asp-for="Gender"></label>
            <input asp-for="Gender" class="form-control" />
            <span asp-validation-for="Gender" class="text-danger"></span>
        </div>
        <div class="mb-2">
            <label asp-for="Profession"></label>
            <input asp-for="Profession" class="form-control" />
            <span asp-validation-for="Profession" class="text-danger"></span>
        </div>
        <button type="submit" class="btn btn-primary" style="width:150px">Update</button>
        <a asp-asp-controller="Userdata" asp-action="Index" class="btn btn-secondary" style="width:150px">Back to List</a>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial.cshtml" />
    }
}

DotNET_Projects/BulkyBook/BulkyBookWeb/Views/Usersdata/Index.cshtml
@model IEnumerable<Usersdata>

@{
    ViewData["Title"] = "Index";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2>User List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Usersdata" asp-action="Create" class="btn btn-primary">Create new user</a>
        </div>
    </div>

<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>
                First Name
            </th>
            <th>
                Last Name
            </th>
            <th>
                Age
            </th>
            <th>
                Gender
            </th>
            <th>
                Profession
            </th>
            <th>

            </th>
        
        </tr>
    </thead>
    <tbody>
        @foreach(var item in Model)
        {
        <tr>
            <td>
               @item.FirstName
            </td>
            <td>
               @item.LastName
            </td>
            <td>
                @item.Age
            </td>
            <td>
                @item.Gender
            </td>
            <td>
                @item.Profession
            </td>
            <td>
                <div class="" role="group">
                    <a asp-controller="Usersdata" asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                </div>
            </td>
            <td>
                <div role="group">
                    <a asp-controller="Usersdata" asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </div>
            </td>
            </tr>
        }
        
    </tbody>
</table>
</div>